Collections:
- Name: NRTR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Epochs: 6
    Batch Size: 6144
    Training Resources: 1x Tesla A100
    Architecture:
      - CNN
      - NRTREncoder
      - NRTRDecoder
  Paper:
    URL: https://arxiv.org/pdf/1806.00926.pdf
    Title: 'NRTR: A No-Recurrence Sequence-to-Sequence Model For Scene Text Recognition'
  README: configs/textrecog/nrtr/README.md

Models:
  - Name: nrtr_resnet31-1by16-1by8_6e_st_mj
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_resnet31-1by16-1by8_6e_st_mj.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 94.8
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 89.03
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 93.79
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 74.19
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 80.31
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 87.15
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by16_1by8_academic_20211124-f60cebf4.pth

  - Name: nrtr_resnet31-1by8-1by4_6e_st_mj
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_resnet31-1by8-1by4_6e_st_mj.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 95.5
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 90.01
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 94.38
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 74.05
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 79.53
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 87.15
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by8_1by4_academic_20211123-e1fdb322.pth
