Collections:
- Name: NRTR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Training Resources: 64x NVIDIA 1080Ti GPUs
    Architecture:
      - ResNet31OCR
      - TFEncoder
      - TFDecoder
  Paper: https://arxiv.org/pdf/1806.00926.pdf
  README: configs/textrecog/nrtr/README.md

Models:
  - Name: nrtr_r31_1by16_1by8_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Regular Text Recognition
        Dataset:
          - IIIT5K
          - SVT
          - ICDAR2013
        Metrics:
          acc:
            - 93.9
            - 90.0
            - 93.5
      - Task: Irregular Text Recognition
        Dataset:
          - ICDAR2015
          - SVTP
          - CT80
        Metrics:
          acc:
            - 74.5
            - 78.5
            - 86.5
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_academic_20210406-954db95e.pth

  - Name: nrtr_r31_1by8_1by4_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Regular Text Recognition
        Dataset:
          - IIIT5K
          - SVT
          - ICDAR2013
        Metrics:
          acc:
            - 94.7
            - 87.5
            - 93.3
      - Task: Irregular Text Recognition
        Dataset:
          - ICDAR2015
          - SVTP
          - CT80
        Metrics:
          acc:
            - 75.1
            - 78.9
            - 87.9
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by8_1by4_academic_20210406-ce16e7cc.pth
